# Generated by Django 4.2.6 on 2023-10-06 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_sale_commission_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sale",
            name="sale_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="commissionsettings",
            name="max_commission",
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name="commissionsettings",
            name="min_commission",
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
